-- Generated by match_v2.ps1
-- Only includes exact-strength matches (score >= 10)
-- 

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE eapts_drug_mapping;
UPDATE drug SET uuid = '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4' WHERE drug_id = 21;
UPDATE drug SET uuid = 'c8c0d27d-6f22-49c3-a4e2-3e73a2d8cbff' WHERE drug_id = 33;
UPDATE drug SET uuid = '50e097f6-fd40-42b6-ac91-d6e95a95b205' WHERE drug_id = 35;
UPDATE drug SET uuid = 'e4aa1f9e-fcd4-4247-856a-65a8cddfd4d3' WHERE drug_id = 36;
UPDATE drug SET uuid = 'ac4bcde4-708d-443b-904e-db7bfbedadb0' WHERE drug_id = 37;
UPDATE drug SET uuid = 'ea001bb4-a11f-47c7-8522-72de75823be0' WHERE drug_id = 40;
UPDATE drug SET uuid = '375de188-bd26-43cc-a113-dfbb0932ce71' WHERE drug_id = 46;
UPDATE drug SET uuid = '0f574c10-5a67-49d1-b382-5b07b8d5b9b7' WHERE drug_id = 47;
UPDATE drug SET uuid = '73b177c3-fb90-465f-9e4b-76d6dfa965ac' WHERE drug_id = 48;
UPDATE drug SET uuid = 'd340d07d-462d-4752-90aa-a872506b09c4' WHERE drug_id = 50;
UPDATE drug SET uuid = 'ab1bc8aa-0295-41af-9bbd-54e112c84400' WHERE drug_id = 51;
UPDATE drug SET uuid = '542656b9-0c1e-4d8b-896e-9f0e8e3cd0b0' WHERE drug_id = 52;
UPDATE drug SET uuid = '88054c4c-1e75-46f6-95fc-7f22154adbdf' WHERE drug_id = 53;
UPDATE drug SET uuid = '36b48a25-c640-4f99-b388-18482bbab517' WHERE drug_id = 57;
UPDATE drug SET uuid = '20a02e2c-2c9a-42aa-9065-2981c34fb119' WHERE drug_id = 62;
UPDATE drug SET uuid = '546a070b-7382-4004-af76-5e32940f9913' WHERE drug_id = 64;
UPDATE drug SET uuid = '0554d85e-9973-4c75-80f7-66b09edc35a7' WHERE drug_id = 66;
UPDATE drug SET uuid = 'b7bba141-2c85-41e8-853b-9f642d06e771' WHERE drug_id = 67;
UPDATE drug SET uuid = 'ea383b1d-a86e-489a-90cf-6fe6b19a7b0e' WHERE drug_id = 69;
UPDATE drug SET uuid = 'a54736e1-7ce1-4e71-a739-ad49ff98b339' WHERE drug_id = 70;
UPDATE drug SET uuid = '6bea70f6-9d51-4149-87d7-5308a8c5dae4' WHERE drug_id = 72;
UPDATE drug SET uuid = '1355e553-f864-4f07-9c09-c9ffd33e45de' WHERE drug_id = 88;
UPDATE drug SET uuid = '68c439e5-8b02-4268-a974-6cd8ab54c85b' WHERE drug_id = 89;
UPDATE drug SET uuid = '0eb899ed-b39f-4d96-891d-afdea7b4bab6' WHERE drug_id = 90;
UPDATE drug SET uuid = '4a1fb000-c3c9-42cf-a8e4-8c81a3c6acf5' WHERE drug_id = 95;
UPDATE drug SET uuid = '36721b44-3dc5-4436-8609-a15d3cb1d757' WHERE drug_id = 97;
UPDATE drug SET uuid = '65a4a533-c8fc-4617-ada8-20deaecde861' WHERE drug_id = 100;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 104;
UPDATE drug SET uuid = 'b71f133a-c8fd-4b35-b425-4e8a632650cd' WHERE drug_id = 105;
UPDATE drug SET uuid = '683b9729-7c7e-4571-b414-d8da47ced13a' WHERE drug_id = 116;
UPDATE drug SET uuid = '124bcd41-f2d9-43f8-bbf8-3bb55b1c3e3a' WHERE drug_id = 118;
UPDATE drug SET uuid = 'bd801d9e-9914-49e1-9b72-435298aad7bb' WHERE drug_id = 119;
UPDATE drug SET uuid = '25d5ba9d-a02f-45d4-9eb5-55687d3a5f02' WHERE drug_id = 121;
UPDATE drug SET uuid = 'e1239202-65c9-41e9-b6e2-e2a3432d4680' WHERE drug_id = 123;
UPDATE drug SET uuid = '5be7c77f-832c-482e-9be2-e8d56475ae09' WHERE drug_id = 124;
UPDATE drug SET uuid = '6396e1cf-5d3b-4508-9a72-0f5b185d35fa' WHERE drug_id = 125;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 126;
UPDATE drug SET uuid = '9812810e-d170-4fbf-9b0b-be13cde8434c' WHERE drug_id = 138;
UPDATE drug SET uuid = '5aff73f2-d53d-473c-a23b-4d34a7dad1f4' WHERE drug_id = 143;
UPDATE drug SET uuid = '7f556295-e3b7-4149-b85c-807fa82dd21e' WHERE drug_id = 156;
UPDATE drug SET uuid = '5b14a966-1db6-4ec2-b504-2bda9035b66a' WHERE drug_id = 159;
UPDATE drug SET uuid = 'c68801bc-2ad5-4ea5-b007-1de879621fea' WHERE drug_id = 160;
UPDATE drug SET uuid = 'a7036cb6-25ac-4719-929f-41f3bf4f9dcb' WHERE drug_id = 162;
UPDATE drug SET uuid = '300e80f0-9db6-4d32-8a9a-de4acc3f48bd' WHERE drug_id = 163;
UPDATE drug SET uuid = '4150fd07-1e49-4573-9eff-7ec2ae163a6d' WHERE drug_id = 169;
UPDATE drug SET uuid = 'e496f186-ca0d-4c6b-bc55-a3fbab9b6b72' WHERE drug_id = 179;
UPDATE drug SET uuid = '7364aa9f-8f19-4f39-a109-6050bd23ad3a' WHERE drug_id = 182;
UPDATE drug SET uuid = '5bac4519-ca41-47dc-b445-2d329ece9c3a' WHERE drug_id = 186;
UPDATE drug SET uuid = '9a8086a0-3bcf-43b4-824e-3a981ab507f9' WHERE drug_id = 189;
UPDATE drug SET uuid = 'fe94593c-5304-49d2-b0f1-f328d35625ad' WHERE drug_id = 194;
UPDATE drug SET uuid = 'd5b9adb2-11c8-42b8-b06e-b8e656a83f1e' WHERE drug_id = 218;
UPDATE drug SET uuid = '3735c2b1-42a0-452e-8e5c-7b98490fd429' WHERE drug_id = 220;
UPDATE drug SET uuid = 'e2ec78c3-a56a-474a-a0cc-e51426f3d990' WHERE drug_id = 235;
UPDATE drug SET uuid = '7e0b0c1a-99e6-47ae-b88e-7dc2b3d01ba0' WHERE drug_id = 236;
UPDATE drug SET uuid = 'b531e1c8-6697-46c1-a11c-37aad2ff9664' WHERE drug_id = 263;
UPDATE drug SET uuid = 'f5ba1908-5fbc-4a8e-bd9a-8ea113bc918f' WHERE drug_id = 276;
UPDATE drug SET uuid = 'be020ada-3b9d-4d82-9976-3314c803be17' WHERE drug_id = 284;
UPDATE drug SET uuid = 'eb6a5051-0faa-4b00-90c2-f9085f927f47' WHERE drug_id = 294;
UPDATE drug SET uuid = 'f472edd1-9bf8-491d-8bcf-de91c9b102cb' WHERE drug_id = 296;
UPDATE drug SET uuid = 'a0cc558d-3cba-483a-99aa-90765fb86f63' WHERE drug_id = 299;
UPDATE drug SET uuid = 'b1d37c58-827c-4c00-aca4-db147288cb2e' WHERE drug_id = 303;
UPDATE drug SET uuid = '528036a0-39e7-4d20-86ba-3b7ee5cd4a83' WHERE drug_id = 347;
UPDATE drug SET uuid = 'edd34296-b668-42d2-889a-442b38300df2' WHERE drug_id = 353;
UPDATE drug SET uuid = 'a33bc6b0-6c38-4e85-a211-152e15658572' WHERE drug_id = 372;
UPDATE drug SET uuid = '49e297b4-6f01-4b71-8ffb-bc014bb806f4' WHERE drug_id = 374;
UPDATE drug SET uuid = '548aecc2-84b2-444e-a896-17ab7a01e02f' WHERE drug_id = 378;
UPDATE drug SET uuid = '88ee9e0d-aac1-4847-8c62-67541d619286' WHERE drug_id = 396;
UPDATE drug SET uuid = '0c38bb0f-6f5e-40f3-be93-3d7ce4649ba5' WHERE drug_id = 437;
UPDATE drug SET uuid = '1d9cb705-5210-4597-8c0a-479ccc0630cc' WHERE drug_id = 456;
UPDATE drug SET uuid = '7ac03015-f26d-42fb-8a4b-6e578789b1e1' WHERE drug_id = 460;
UPDATE drug SET uuid = 'dd7145a4-ac5a-4ece-bc35-7fd1b8aa528a' WHERE drug_id = 481;
UPDATE drug SET uuid = '5d6d9573-6284-4672-8e5f-2a1bf620a6a7' WHERE drug_id = 482;
UPDATE drug SET uuid = '6336a316-3c94-4bef-a6c3-b80464aee9dd' WHERE drug_id = 508;

INSERT INTO eapts_drug_mapping (openmrs_drug_id, dagu_item_uuid, created_date) VALUES
  (21, '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4', NOW()),
  (33, 'c8c0d27d-6f22-49c3-a4e2-3e73a2d8cbff', NOW()),
  (35, '50e097f6-fd40-42b6-ac91-d6e95a95b205', NOW()),
  (36, 'e4aa1f9e-fcd4-4247-856a-65a8cddfd4d3', NOW()),
  (37, 'ac4bcde4-708d-443b-904e-db7bfbedadb0', NOW()),
  (40, 'ea001bb4-a11f-47c7-8522-72de75823be0', NOW()),
  (46, '375de188-bd26-43cc-a113-dfbb0932ce71', NOW()),
  (47, '0f574c10-5a67-49d1-b382-5b07b8d5b9b7', NOW()),
  (48, '73b177c3-fb90-465f-9e4b-76d6dfa965ac', NOW()),
  (50, 'd340d07d-462d-4752-90aa-a872506b09c4', NOW()),
  (51, 'ab1bc8aa-0295-41af-9bbd-54e112c84400', NOW()),
  (52, '542656b9-0c1e-4d8b-896e-9f0e8e3cd0b0', NOW()),
  (53, '88054c4c-1e75-46f6-95fc-7f22154adbdf', NOW()),
  (57, '36b48a25-c640-4f99-b388-18482bbab517', NOW()),
  (62, '20a02e2c-2c9a-42aa-9065-2981c34fb119', NOW()),
  (64, '546a070b-7382-4004-af76-5e32940f9913', NOW()),
  (66, '0554d85e-9973-4c75-80f7-66b09edc35a7', NOW()),
  (67, 'b7bba141-2c85-41e8-853b-9f642d06e771', NOW()),
  (69, 'ea383b1d-a86e-489a-90cf-6fe6b19a7b0e', NOW()),
  (70, 'a54736e1-7ce1-4e71-a739-ad49ff98b339', NOW()),
  (72, '6bea70f6-9d51-4149-87d7-5308a8c5dae4', NOW()),
  (88, '1355e553-f864-4f07-9c09-c9ffd33e45de', NOW()),
  (89, '68c439e5-8b02-4268-a974-6cd8ab54c85b', NOW()),
  (90, '0eb899ed-b39f-4d96-891d-afdea7b4bab6', NOW()),
  (95, '4a1fb000-c3c9-42cf-a8e4-8c81a3c6acf5', NOW()),
  (97, '36721b44-3dc5-4436-8609-a15d3cb1d757', NOW()),
  (100, '65a4a533-c8fc-4617-ada8-20deaecde861', NOW()),
  (104, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (105, 'b71f133a-c8fd-4b35-b425-4e8a632650cd', NOW()),
  (116, '683b9729-7c7e-4571-b414-d8da47ced13a', NOW()),
  (118, '124bcd41-f2d9-43f8-bbf8-3bb55b1c3e3a', NOW()),
  (119, 'bd801d9e-9914-49e1-9b72-435298aad7bb', NOW()),
  (121, '25d5ba9d-a02f-45d4-9eb5-55687d3a5f02', NOW()),
  (123, 'e1239202-65c9-41e9-b6e2-e2a3432d4680', NOW()),
  (124, '5be7c77f-832c-482e-9be2-e8d56475ae09', NOW()),
  (125, '6396e1cf-5d3b-4508-9a72-0f5b185d35fa', NOW()),
  (126, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (138, '9812810e-d170-4fbf-9b0b-be13cde8434c', NOW()),
  (143, '5aff73f2-d53d-473c-a23b-4d34a7dad1f4', NOW()),
  (156, '7f556295-e3b7-4149-b85c-807fa82dd21e', NOW()),
  (159, '5b14a966-1db6-4ec2-b504-2bda9035b66a', NOW()),
  (160, 'c68801bc-2ad5-4ea5-b007-1de879621fea', NOW()),
  (162, 'a7036cb6-25ac-4719-929f-41f3bf4f9dcb', NOW()),
  (163, '300e80f0-9db6-4d32-8a9a-de4acc3f48bd', NOW()),
  (169, '4150fd07-1e49-4573-9eff-7ec2ae163a6d', NOW()),
  (179, 'e496f186-ca0d-4c6b-bc55-a3fbab9b6b72', NOW()),
  (182, '7364aa9f-8f19-4f39-a109-6050bd23ad3a', NOW()),
  (186, '5bac4519-ca41-47dc-b445-2d329ece9c3a', NOW()),
  (189, '9a8086a0-3bcf-43b4-824e-3a981ab507f9', NOW()),
  (194, 'fe94593c-5304-49d2-b0f1-f328d35625ad', NOW()),
  (218, 'd5b9adb2-11c8-42b8-b06e-b8e656a83f1e', NOW()),
  (220, '3735c2b1-42a0-452e-8e5c-7b98490fd429', NOW()),
  (235, 'e2ec78c3-a56a-474a-a0cc-e51426f3d990', NOW()),
  (236, '7e0b0c1a-99e6-47ae-b88e-7dc2b3d01ba0', NOW()),
  (263, 'b531e1c8-6697-46c1-a11c-37aad2ff9664', NOW()),
  (276, 'f5ba1908-5fbc-4a8e-bd9a-8ea113bc918f', NOW()),
  (284, 'be020ada-3b9d-4d82-9976-3314c803be17', NOW()),
  (294, 'eb6a5051-0faa-4b00-90c2-f9085f927f47', NOW()),
  (296, 'f472edd1-9bf8-491d-8bcf-de91c9b102cb', NOW()),
  (299, 'a0cc558d-3cba-483a-99aa-90765fb86f63', NOW()),
  (303, 'b1d37c58-827c-4c00-aca4-db147288cb2e', NOW()),
  (347, '528036a0-39e7-4d20-86ba-3b7ee5cd4a83', NOW()),
  (353, 'edd34296-b668-42d2-889a-442b38300df2', NOW()),
  (372, 'a33bc6b0-6c38-4e85-a211-152e15658572', NOW()),
  (374, '49e297b4-6f01-4b71-8ffb-bc014bb806f4', NOW()),
  (378, '548aecc2-84b2-444e-a896-17ab7a01e02f', NOW()),
  (396, '88ee9e0d-aac1-4847-8c62-67541d619286', NOW()),
  (437, '0c38bb0f-6f5e-40f3-be93-3d7ce4649ba5', NOW()),
  (456, '1d9cb705-5210-4597-8c0a-479ccc0630cc', NOW()),
  (460, '7ac03015-f26d-42fb-8a4b-6e578789b1e1', NOW()),
  (481, 'dd7145a4-ac5a-4ece-bc35-7fd1b8aa528a', NOW()),
  (482, '5d6d9573-6284-4672-8e5f-2a1bf620a6a7', NOW()),
  (508, '6336a316-3c94-4bef-a6c3-b80464aee9dd', NOW());

SET FOREIGN_KEY_CHECKS = 1;
