-- Generated by match_and_map.ps1
-- Date: 2026-06-26 13:39:47
--
-- This script:
-- 1. Updates OpenMRS drug UUIDs to match Dagu item_unit UUIDs
-- 2. Creates eapts_drug_mapping entries for all matched drugs
--

SET FOREIGN_KEY_CHECKS = 0;

-- Clear existing mappings
TRUNCATE TABLE eapts_drug_mapping;

-- Update drug UUIDs
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 12;
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 13;
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 14;
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 15;
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 18;
UPDATE drug SET uuid = 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526' WHERE drug_id = 19;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 28;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 29;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 30;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 31;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 32;
UPDATE drug SET uuid = '25d5ba9d-a02f-45d4-9eb5-55687d3a5f02' WHERE drug_id = 33;
UPDATE drug SET uuid = '32e586b5-174a-4690-970e-9e40599ff2ba' WHERE drug_id = 34;
UPDATE drug SET uuid = '6092bf43-269a-44bb-8eca-b83079ec2ee8' WHERE drug_id = 35;
UPDATE drug SET uuid = '6092bf43-269a-44bb-8eca-b83079ec2ee8' WHERE drug_id = 36;
UPDATE drug SET uuid = '6092bf43-269a-44bb-8eca-b83079ec2ee8' WHERE drug_id = 37;
UPDATE drug SET uuid = '002f0494-c0f0-4118-8184-597c0a4fd895' WHERE drug_id = 38;
UPDATE drug SET uuid = '002f0494-c0f0-4118-8184-597c0a4fd895' WHERE drug_id = 39;
UPDATE drug SET uuid = '23c32d7f-9586-4446-b17c-35e464e97e15' WHERE drug_id = 40;
UPDATE drug SET uuid = '23c32d7f-9586-4446-b17c-35e464e97e15' WHERE drug_id = 41;
UPDATE drug SET uuid = '7953e859-386b-4112-9e6e-a88785271b09' WHERE drug_id = 42;
UPDATE drug SET uuid = '23c32d7f-9586-4446-b17c-35e464e97e15' WHERE drug_id = 43;
UPDATE drug SET uuid = '23c32d7f-9586-4446-b17c-35e464e97e15' WHERE drug_id = 44;
UPDATE drug SET uuid = '0f574c10-5a67-49d1-b382-5b07b8d5b9b7' WHERE drug_id = 47;
UPDATE drug SET uuid = '0f574c10-5a67-49d1-b382-5b07b8d5b9b7' WHERE drug_id = 48;
UPDATE drug SET uuid = 'b093d92f-48d4-477a-8d47-aa498a743fe5' WHERE drug_id = 49;
UPDATE drug SET uuid = '77f8e799-b6b4-47ad-8661-a4b4cddf2964' WHERE drug_id = 50;
UPDATE drug SET uuid = '77f8e799-b6b4-47ad-8661-a4b4cddf2964' WHERE drug_id = 51;
UPDATE drug SET uuid = '8c690c34-0324-4a81-914e-4668f539d152' WHERE drug_id = 63;
UPDATE drug SET uuid = '0554d85e-9973-4c75-80f7-66b09edc35a7' WHERE drug_id = 66;
UPDATE drug SET uuid = '0554d85e-9973-4c75-80f7-66b09edc35a7' WHERE drug_id = 67;
UPDATE drug SET uuid = '104f51e6-d35c-4164-a253-0a96b3b849fb' WHERE drug_id = 68;
UPDATE drug SET uuid = '104f51e6-d35c-4164-a253-0a96b3b849fb' WHERE drug_id = 69;
UPDATE drug SET uuid = 'a54736e1-7ce1-4e71-a739-ad49ff98b339' WHERE drug_id = 70;
UPDATE drug SET uuid = '4f665cf1-e8e8-4c33-89c3-ad195ab9185f' WHERE drug_id = 72;
UPDATE drug SET uuid = '4f665cf1-e8e8-4c33-89c3-ad195ab9185f' WHERE drug_id = 73;
UPDATE drug SET uuid = '4f665cf1-e8e8-4c33-89c3-ad195ab9185f' WHERE drug_id = 74;
UPDATE drug SET uuid = '4f665cf1-e8e8-4c33-89c3-ad195ab9185f' WHERE drug_id = 75;
UPDATE drug SET uuid = 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526' WHERE drug_id = 77;
UPDATE drug SET uuid = '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e' WHERE drug_id = 78;
UPDATE drug SET uuid = '95adca5f-554b-4408-8634-dc7b47b7e5cc' WHERE drug_id = 80;
UPDATE drug SET uuid = '63529860-834e-4b40-a2ba-7873614a091c' WHERE drug_id = 85;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 86;
UPDATE drug SET uuid = '78b4cb66-4794-4d81-a0b7-2a8fbba5c419' WHERE drug_id = 87;
UPDATE drug SET uuid = '1aff9318-6780-40de-8370-36c2418c2993' WHERE drug_id = 88;
UPDATE drug SET uuid = '1aff9318-6780-40de-8370-36c2418c2993' WHERE drug_id = 89;
UPDATE drug SET uuid = '1aff9318-6780-40de-8370-36c2418c2993' WHERE drug_id = 90;
UPDATE drug SET uuid = '1aff9318-6780-40de-8370-36c2418c2993' WHERE drug_id = 91;
UPDATE drug SET uuid = '1aff9318-6780-40de-8370-36c2418c2993' WHERE drug_id = 92;
UPDATE drug SET uuid = '0c5779f5-f552-4ee1-9b68-d870ea28fb4a' WHERE drug_id = 93;
UPDATE drug SET uuid = '0c5779f5-f552-4ee1-9b68-d870ea28fb4a' WHERE drug_id = 94;
UPDATE drug SET uuid = '0c5779f5-f552-4ee1-9b68-d870ea28fb4a' WHERE drug_id = 95;
UPDATE drug SET uuid = '22d40505-e112-4878-b8d2-579d094214d7' WHERE drug_id = 99;
UPDATE drug SET uuid = '07e8ff99-5571-4b26-9ab9-3bb38cca55c6' WHERE drug_id = 100;
UPDATE drug SET uuid = '07e8ff99-5571-4b26-9ab9-3bb38cca55c6' WHERE drug_id = 101;
UPDATE drug SET uuid = '07e8ff99-5571-4b26-9ab9-3bb38cca55c6' WHERE drug_id = 102;
UPDATE drug SET uuid = '07e8ff99-5571-4b26-9ab9-3bb38cca55c6' WHERE drug_id = 103;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 104;
UPDATE drug SET uuid = 'fab228c6-ca7f-4d1a-abe8-f7ef2664b5b8' WHERE drug_id = 105;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 106;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 107;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 108;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 109;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 110;
UPDATE drug SET uuid = '0f312df0-4cfd-4774-9666-a05f3da7a35d' WHERE drug_id = 111;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 112;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 113;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 114;
UPDATE drug SET uuid = '78b4cb66-4794-4d81-a0b7-2a8fbba5c419' WHERE drug_id = 115;
UPDATE drug SET uuid = '0e77cc78-2967-4073-9b7f-40d641259af6' WHERE drug_id = 116;
UPDATE drug SET uuid = '0e77cc78-2967-4073-9b7f-40d641259af6' WHERE drug_id = 117;
UPDATE drug SET uuid = '124bcd41-f2d9-43f8-bbf8-3bb55b1c3e3a' WHERE drug_id = 118;
UPDATE drug SET uuid = 'a411cbd3-df5a-4ce1-a004-098fb6f52fe9' WHERE drug_id = 119;
UPDATE drug SET uuid = '479e66e8-5b86-4a45-8066-52f4db4164a6' WHERE drug_id = 123;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 124;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 125;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 126;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 127;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 128;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 129;
UPDATE drug SET uuid = '4f119f61-938f-4e37-893a-450b9edca202' WHERE drug_id = 130;
UPDATE drug SET uuid = '0a549ecc-a7c0-4e87-8e71-dde09483655e' WHERE drug_id = 131;
UPDATE drug SET uuid = '003b0694-c0cd-43cf-abee-86aae6992b96' WHERE drug_id = 132;
UPDATE drug SET uuid = '4edc1934-0f23-4faf-a5eb-7422b5ec5940' WHERE drug_id = 133;
UPDATE drug SET uuid = '4edc1934-0f23-4faf-a5eb-7422b5ec5940' WHERE drug_id = 134;
UPDATE drug SET uuid = '4edc1934-0f23-4faf-a5eb-7422b5ec5940' WHERE drug_id = 135;
UPDATE drug SET uuid = '4edc1934-0f23-4faf-a5eb-7422b5ec5940' WHERE drug_id = 136;
UPDATE drug SET uuid = '3ddac5dc-b117-4d11-a01e-ae123060510f' WHERE drug_id = 137;
UPDATE drug SET uuid = '3ddac5dc-b117-4d11-a01e-ae123060510f' WHERE drug_id = 138;
UPDATE drug SET uuid = '3ddac5dc-b117-4d11-a01e-ae123060510f' WHERE drug_id = 139;
UPDATE drug SET uuid = '5aff73f2-d53d-473c-a23b-4d34a7dad1f4' WHERE drug_id = 142;
UPDATE drug SET uuid = '5aff73f2-d53d-473c-a23b-4d34a7dad1f4' WHERE drug_id = 143;
UPDATE drug SET uuid = '5aff73f2-d53d-473c-a23b-4d34a7dad1f4' WHERE drug_id = 144;
UPDATE drug SET uuid = '5aff73f2-d53d-473c-a23b-4d34a7dad1f4' WHERE drug_id = 145;
UPDATE drug SET uuid = 'fdcac0df-1cf0-4ef0-8641-4fdbd5fc6cfa' WHERE drug_id = 146;
UPDATE drug SET uuid = 'fdcac0df-1cf0-4ef0-8641-4fdbd5fc6cfa' WHERE drug_id = 147;
UPDATE drug SET uuid = 'fdcac0df-1cf0-4ef0-8641-4fdbd5fc6cfa' WHERE drug_id = 148;
UPDATE drug SET uuid = 'e70caf0b-f17c-4acc-9321-4891ce302597' WHERE drug_id = 149;
UPDATE drug SET uuid = 'e70caf0b-f17c-4acc-9321-4891ce302597' WHERE drug_id = 150;
UPDATE drug SET uuid = '4e17f09e-1e15-4d21-8b0a-34277d61d41a' WHERE drug_id = 151;
UPDATE drug SET uuid = '4e17f09e-1e15-4d21-8b0a-34277d61d41a' WHERE drug_id = 152;
UPDATE drug SET uuid = '4e17f09e-1e15-4d21-8b0a-34277d61d41a' WHERE drug_id = 153;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 154;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 155;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 156;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 157;
UPDATE drug SET uuid = '324a63ce-ee32-44f0-aac6-7d240e3041fe' WHERE drug_id = 158;
UPDATE drug SET uuid = '324a63ce-ee32-44f0-aac6-7d240e3041fe' WHERE drug_id = 159;
UPDATE drug SET uuid = '324a63ce-ee32-44f0-aac6-7d240e3041fe' WHERE drug_id = 160;
UPDATE drug SET uuid = '324a63ce-ee32-44f0-aac6-7d240e3041fe' WHERE drug_id = 161;
UPDATE drug SET uuid = '11223f2a-e361-437a-8328-37b2e7234466' WHERE drug_id = 162;
UPDATE drug SET uuid = '11223f2a-e361-437a-8328-37b2e7234466' WHERE drug_id = 163;
UPDATE drug SET uuid = 'e84f1938-aca7-4217-a99d-dbe879772273' WHERE drug_id = 164;
UPDATE drug SET uuid = '11223f2a-e361-437a-8328-37b2e7234466' WHERE drug_id = 165;
UPDATE drug SET uuid = '20c66d34-5a48-482b-b132-5ba37c7a65e8' WHERE drug_id = 166;
UPDATE drug SET uuid = '20c66d34-5a48-482b-b132-5ba37c7a65e8' WHERE drug_id = 167;
UPDATE drug SET uuid = '20c66d34-5a48-482b-b132-5ba37c7a65e8' WHERE drug_id = 168;
UPDATE drug SET uuid = '1fb54d96-33ae-4f46-9542-1f98c923b394' WHERE drug_id = 169;
UPDATE drug SET uuid = '48664ddb-6229-4cde-ab1a-647d0da6cdff' WHERE drug_id = 170;
UPDATE drug SET uuid = '3f126a01-64dd-4674-80a2-f48077645c34' WHERE drug_id = 171;
UPDATE drug SET uuid = '089ac445-a53a-4415-b7ae-0c706c43e902' WHERE drug_id = 172;
UPDATE drug SET uuid = '089ac445-a53a-4415-b7ae-0c706c43e902' WHERE drug_id = 173;
UPDATE drug SET uuid = '9632bae1-83ff-430c-84da-583e96ccfc46' WHERE drug_id = 174;
UPDATE drug SET uuid = '0bf8ec68-b606-4111-98eb-35eb3452be72' WHERE drug_id = 182;
UPDATE drug SET uuid = '0bf8ec68-b606-4111-98eb-35eb3452be72' WHERE drug_id = 183;
UPDATE drug SET uuid = '717d2642-a4c2-4c50-868e-5c025d8e18a9' WHERE drug_id = 185;
UPDATE drug SET uuid = '5bac4519-ca41-47dc-b445-2d329ece9c3a' WHERE drug_id = 186;
UPDATE drug SET uuid = '0151c78f-a53d-4ebe-afe2-b0e652827db7' WHERE drug_id = 187;
UPDATE drug SET uuid = '0151c78f-a53d-4ebe-afe2-b0e652827db7' WHERE drug_id = 188;
UPDATE drug SET uuid = '0151c78f-a53d-4ebe-afe2-b0e652827db7' WHERE drug_id = 189;
UPDATE drug SET uuid = '0151c78f-a53d-4ebe-afe2-b0e652827db7' WHERE drug_id = 190;
UPDATE drug SET uuid = '0151c78f-a53d-4ebe-afe2-b0e652827db7' WHERE drug_id = 191;
UPDATE drug SET uuid = '5bac4519-ca41-47dc-b445-2d329ece9c3a' WHERE drug_id = 192;
UPDATE drug SET uuid = '4bbb95a3-9f49-4b65-b462-fc247db1fab0' WHERE drug_id = 193;
UPDATE drug SET uuid = '4bbb95a3-9f49-4b65-b462-fc247db1fab0' WHERE drug_id = 194;
UPDATE drug SET uuid = '4bbb95a3-9f49-4b65-b462-fc247db1fab0' WHERE drug_id = 195;
UPDATE drug SET uuid = '073674e3-35a7-4fcc-9317-611d8d5b532d' WHERE drug_id = 196;
UPDATE drug SET uuid = '073674e3-35a7-4fcc-9317-611d8d5b532d' WHERE drug_id = 197;
UPDATE drug SET uuid = '073674e3-35a7-4fcc-9317-611d8d5b532d' WHERE drug_id = 198;
UPDATE drug SET uuid = '073674e3-35a7-4fcc-9317-611d8d5b532d' WHERE drug_id = 199;
UPDATE drug SET uuid = '073674e3-35a7-4fcc-9317-611d8d5b532d' WHERE drug_id = 200;
UPDATE drug SET uuid = '18702c41-e66d-455e-bf4b-35099adb04dc' WHERE drug_id = 209;
UPDATE drug SET uuid = '089ac445-a53a-4415-b7ae-0c706c43e902' WHERE drug_id = 210;
UPDATE drug SET uuid = '098bbf71-34cf-4582-925d-7998bb75ef7f' WHERE drug_id = 213;
UPDATE drug SET uuid = '20365026-a221-4d9d-8160-3f2cdb17000b' WHERE drug_id = 214;
UPDATE drug SET uuid = '20365026-a221-4d9d-8160-3f2cdb17000b' WHERE drug_id = 215;
UPDATE drug SET uuid = '20365026-a221-4d9d-8160-3f2cdb17000b' WHERE drug_id = 216;
UPDATE drug SET uuid = '20365026-a221-4d9d-8160-3f2cdb17000b' WHERE drug_id = 217;
UPDATE drug SET uuid = '16cf30d5-24b4-4b3e-88ce-19ec1ea19772' WHERE drug_id = 218;
UPDATE drug SET uuid = '16cf30d5-24b4-4b3e-88ce-19ec1ea19772' WHERE drug_id = 219;
UPDATE drug SET uuid = '16cf30d5-24b4-4b3e-88ce-19ec1ea19772' WHERE drug_id = 220;
UPDATE drug SET uuid = '16cf30d5-24b4-4b3e-88ce-19ec1ea19772' WHERE drug_id = 221;
UPDATE drug SET uuid = '16cf30d5-24b4-4b3e-88ce-19ec1ea19772' WHERE drug_id = 222;
UPDATE drug SET uuid = '16cf30d5-24b4-4b3e-88ce-19ec1ea19772' WHERE drug_id = 223;
UPDATE drug SET uuid = '16cf30d5-24b4-4b3e-88ce-19ec1ea19772' WHERE drug_id = 224;
UPDATE drug SET uuid = '1d9e1df4-8aea-4973-a82e-cf781fe6019f' WHERE drug_id = 228;
UPDATE drug SET uuid = '1d9e1df4-8aea-4973-a82e-cf781fe6019f' WHERE drug_id = 229;
UPDATE drug SET uuid = '12c84b53-f884-42df-83a9-14d32808d233' WHERE drug_id = 230;
UPDATE drug SET uuid = '12c84b53-f884-42df-83a9-14d32808d233' WHERE drug_id = 231;
UPDATE drug SET uuid = '12c84b53-f884-42df-83a9-14d32808d233' WHERE drug_id = 232;
UPDATE drug SET uuid = '1e5a30ad-627c-4094-904d-eaa6df904d91' WHERE drug_id = 242;
UPDATE drug SET uuid = '1e5a30ad-627c-4094-904d-eaa6df904d91' WHERE drug_id = 243;
UPDATE drug SET uuid = '1e5a30ad-627c-4094-904d-eaa6df904d91' WHERE drug_id = 244;
UPDATE drug SET uuid = 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9' WHERE drug_id = 245;
UPDATE drug SET uuid = 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9' WHERE drug_id = 246;
UPDATE drug SET uuid = '7a46c8f1-4ae8-4e06-9246-edf5ceb5d73f' WHERE drug_id = 247;
UPDATE drug SET uuid = '00e31734-ce75-4354-98fb-ab3a35dd71e9' WHERE drug_id = 254;
UPDATE drug SET uuid = '1209780f-80c9-4397-9d54-1cfca2c3b9f0' WHERE drug_id = 255;
UPDATE drug SET uuid = '002f0494-c0f0-4118-8184-597c0a4fd895' WHERE drug_id = 257;
UPDATE drug SET uuid = 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9' WHERE drug_id = 258;
UPDATE drug SET uuid = '1bfdbc7a-96a5-42e4-9aab-c45b94750949' WHERE drug_id = 276;
UPDATE drug SET uuid = '1bfdbc7a-96a5-42e4-9aab-c45b94750949' WHERE drug_id = 277;
UPDATE drug SET uuid = '1bfdbc7a-96a5-42e4-9aab-c45b94750949' WHERE drug_id = 278;
UPDATE drug SET uuid = '1bfdbc7a-96a5-42e4-9aab-c45b94750949' WHERE drug_id = 279;
UPDATE drug SET uuid = '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4' WHERE drug_id = 289;
UPDATE drug SET uuid = '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4' WHERE drug_id = 290;
UPDATE drug SET uuid = '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4' WHERE drug_id = 291;
UPDATE drug SET uuid = '414d23db-7f64-494b-bc47-864642267708' WHERE drug_id = 292;
UPDATE drug SET uuid = '414d23db-7f64-494b-bc47-864642267708' WHERE drug_id = 293;
UPDATE drug SET uuid = '0bfed41e-4163-48dd-bd3a-8a0d2bd7b17a' WHERE drug_id = 294;
UPDATE drug SET uuid = '0bfed41e-4163-48dd-bd3a-8a0d2bd7b17a' WHERE drug_id = 295;
UPDATE drug SET uuid = '012b142a-c84a-40bd-8e0a-847d27e5c651' WHERE drug_id = 296;
UPDATE drug SET uuid = '012b142a-c84a-40bd-8e0a-847d27e5c651' WHERE drug_id = 297;
UPDATE drug SET uuid = '0ea731fb-c47e-44e5-8499-8e159e9fe912' WHERE drug_id = 299;
UPDATE drug SET uuid = '0ea731fb-c47e-44e5-8499-8e159e9fe912' WHERE drug_id = 300;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 310;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 311;
UPDATE drug SET uuid = '788f1cdd-e663-40d5-85bb-4ef7fa09967d' WHERE drug_id = 312;
UPDATE drug SET uuid = 'dabd4d3a-0d27-48b7-89fd-13a2801efa8e' WHERE drug_id = 319;
UPDATE drug SET uuid = 'bdac07c7-5e9b-4c42-bc1e-be1d9c9cf726' WHERE drug_id = 320;
UPDATE drug SET uuid = 'bdac07c7-5e9b-4c42-bc1e-be1d9c9cf726' WHERE drug_id = 321;
UPDATE drug SET uuid = 'c8a317cd-4bfb-4041-971b-dec17c98b297' WHERE drug_id = 322;
UPDATE drug SET uuid = 'c8a317cd-4bfb-4041-971b-dec17c98b297' WHERE drug_id = 323;
UPDATE drug SET uuid = '39552d94-e958-4370-a622-8eedb8dcedaf' WHERE drug_id = 325;
UPDATE drug SET uuid = '39552d94-e958-4370-a622-8eedb8dcedaf' WHERE drug_id = 326;
UPDATE drug SET uuid = 'b5a92c9a-02ae-4b70-9e21-8adc0e65a20d' WHERE drug_id = 328;
UPDATE drug SET uuid = '319a345f-8351-4bd5-8d3d-c624adc0f11a' WHERE drug_id = 330;
UPDATE drug SET uuid = 'd4f86398-1199-4431-a7fd-b7f8046dcbf4' WHERE drug_id = 332;
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 336;
UPDATE drug SET uuid = '550c2a8d-21d3-4ded-aee8-a653a68ae97f' WHERE drug_id = 343;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 346;
UPDATE drug SET uuid = '012b142a-c84a-40bd-8e0a-847d27e5c651' WHERE drug_id = 350;
UPDATE drug SET uuid = '0e09edd4-a194-461c-a010-aa44bd1c50db' WHERE drug_id = 353;
UPDATE drug SET uuid = '0e09edd4-a194-461c-a010-aa44bd1c50db' WHERE drug_id = 354;
UPDATE drug SET uuid = '717d2642-a4c2-4c50-868e-5c025d8e18a9' WHERE drug_id = 355;
UPDATE drug SET uuid = 'a2e2d9cb-179e-45bc-8e4a-c9160407e96d' WHERE drug_id = 356;
UPDATE drug SET uuid = 'a2e2d9cb-179e-45bc-8e4a-c9160407e96d' WHERE drug_id = 357;
UPDATE drug SET uuid = '88b852e6-b43b-4071-b057-1b1fe00a8e79' WHERE drug_id = 372;
UPDATE drug SET uuid = '88b852e6-b43b-4071-b057-1b1fe00a8e79' WHERE drug_id = 373;
UPDATE drug SET uuid = '49e297b4-6f01-4b71-8ffb-bc014bb806f4' WHERE drug_id = 374;
UPDATE drug SET uuid = '542656b9-0c1e-4d8b-896e-9f0e8e3cd0b0' WHERE drug_id = 375;
UPDATE drug SET uuid = '548aecc2-84b2-444e-a896-17ab7a01e02f' WHERE drug_id = 378;
UPDATE drug SET uuid = 'a54736e1-7ce1-4e71-a739-ad49ff98b339' WHERE drug_id = 379;
UPDATE drug SET uuid = 'a54736e1-7ce1-4e71-a739-ad49ff98b339' WHERE drug_id = 380;
UPDATE drug SET uuid = 'a54736e1-7ce1-4e71-a739-ad49ff98b339' WHERE drug_id = 381;
UPDATE drug SET uuid = '4f665cf1-e8e8-4c33-89c3-ad195ab9185f' WHERE drug_id = 386;
UPDATE drug SET uuid = '5326364f-8c9a-48fe-9a3d-46b44da82d2f' WHERE drug_id = 387;
UPDATE drug SET uuid = '5326364f-8c9a-48fe-9a3d-46b44da82d2f' WHERE drug_id = 388;
UPDATE drug SET uuid = 'ac2b070b-c362-4314-8d5b-1899c297ec4d' WHERE drug_id = 391;
UPDATE drug SET uuid = '043bac44-b808-4c62-acae-f83b6dd2ef09' WHERE drug_id = 394;
UPDATE drug SET uuid = '57228cdc-2269-44ea-ad2d-65a92f03e12a' WHERE drug_id = 395;
UPDATE drug SET uuid = '245a5c30-f5c8-4394-b89e-57fd71faa4a1' WHERE drug_id = 396;
UPDATE drug SET uuid = '245a5c30-f5c8-4394-b89e-57fd71faa4a1' WHERE drug_id = 397;
UPDATE drug SET uuid = '245a5c30-f5c8-4394-b89e-57fd71faa4a1' WHERE drug_id = 398;
UPDATE drug SET uuid = '043bac44-b808-4c62-acae-f83b6dd2ef09' WHERE drug_id = 399;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 400;
UPDATE drug SET uuid = '073674e3-35a7-4fcc-9317-611d8d5b532d' WHERE drug_id = 412;
UPDATE drug SET uuid = '11223f2a-e361-437a-8328-37b2e7234466' WHERE drug_id = 413;
UPDATE drug SET uuid = '11223f2a-e361-437a-8328-37b2e7234466' WHERE drug_id = 414;
UPDATE drug SET uuid = '3f130339-2f34-4850-b88b-94de606df3a1' WHERE drug_id = 415;
UPDATE drug SET uuid = '3a52076c-d186-4aae-9d7a-901e52b27998' WHERE drug_id = 416;
UPDATE drug SET uuid = 'c8a317cd-4bfb-4041-971b-dec17c98b297' WHERE drug_id = 417;
UPDATE drug SET uuid = 'c8a317cd-4bfb-4041-971b-dec17c98b297' WHERE drug_id = 418;
UPDATE drug SET uuid = '4f665cf1-e8e8-4c33-89c3-ad195ab9185f' WHERE drug_id = 419;
UPDATE drug SET uuid = '4f665cf1-e8e8-4c33-89c3-ad195ab9185f' WHERE drug_id = 420;
UPDATE drug SET uuid = 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526' WHERE drug_id = 427;
UPDATE drug SET uuid = 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526' WHERE drug_id = 428;
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 430;
UPDATE drug SET uuid = '143f94c0-774f-41f2-9b12-13dc97cffd4f' WHERE drug_id = 431;
UPDATE drug SET uuid = '9d2a779a-0bae-4592-9b21-50fa03a276fa' WHERE drug_id = 440;
UPDATE drug SET uuid = '9d2a779a-0bae-4592-9b21-50fa03a276fa' WHERE drug_id = 441;
UPDATE drug SET uuid = '23fe72a4-72de-45a2-b627-bafac382e3e1' WHERE drug_id = 442;
UPDATE drug SET uuid = '23fe72a4-72de-45a2-b627-bafac382e3e1' WHERE drug_id = 443;
UPDATE drug SET uuid = '39552d94-e958-4370-a622-8eedb8dcedaf' WHERE drug_id = 444;
UPDATE drug SET uuid = '1d9cb705-5210-4597-8c0a-479ccc0630cc' WHERE drug_id = 445;
UPDATE drug SET uuid = '3735c2b1-42a0-452e-8e5c-7b98490fd429' WHERE drug_id = 450;
UPDATE drug SET uuid = '3735c2b1-42a0-452e-8e5c-7b98490fd429' WHERE drug_id = 451;
UPDATE drug SET uuid = '3735c2b1-42a0-452e-8e5c-7b98490fd429' WHERE drug_id = 452;
UPDATE drug SET uuid = '3735c2b1-42a0-452e-8e5c-7b98490fd429' WHERE drug_id = 453;
UPDATE drug SET uuid = '069bcc18-902c-4030-9030-0b3e723383a4' WHERE drug_id = 459;
UPDATE drug SET uuid = 'a54736e1-7ce1-4e71-a739-ad49ff98b339' WHERE drug_id = 476;
UPDATE drug SET uuid = 'a54736e1-7ce1-4e71-a739-ad49ff98b339' WHERE drug_id = 477;
UPDATE drug SET uuid = '36721b44-3dc5-4436-8609-a15d3cb1d757' WHERE drug_id = 480;
UPDATE drug SET uuid = '36721b44-3dc5-4436-8609-a15d3cb1d757' WHERE drug_id = 481;
UPDATE drug SET uuid = '36721b44-3dc5-4436-8609-a15d3cb1d757' WHERE drug_id = 482;
UPDATE drug SET uuid = '80daa25a-d28c-45a0-9816-2adbd9374975' WHERE drug_id = 483;
UPDATE drug SET uuid = '36721b44-3dc5-4436-8609-a15d3cb1d757' WHERE drug_id = 484;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 487;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 488;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 489;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 490;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 491;
UPDATE drug SET uuid = '63529860-834e-4b40-a2ba-7873614a091c' WHERE drug_id = 492;
UPDATE drug SET uuid = '63529860-834e-4b40-a2ba-7873614a091c' WHERE drug_id = 493;
UPDATE drug SET uuid = '0f77d4c2-9eba-4749-87df-7a0cba14698d' WHERE drug_id = 494;
UPDATE drug SET uuid = '003b0694-c0cd-43cf-abee-86aae6992b96' WHERE drug_id = 495;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 496;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 497;
UPDATE drug SET uuid = '20742023-34b0-4b3a-9693-506174af1bcc' WHERE drug_id = 498;
UPDATE drug SET uuid = 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9' WHERE drug_id = 499;
UPDATE drug SET uuid = '002f0494-c0f0-4118-8184-597c0a4fd895' WHERE drug_id = 500;
UPDATE drug SET uuid = '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e' WHERE drug_id = 501;
UPDATE drug SET uuid = '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e' WHERE drug_id = 502;
UPDATE drug SET uuid = 'a704474b-e2f7-4201-93a8-4f93885eafe3' WHERE drug_id = 507;
UPDATE drug SET uuid = '6336a316-3c94-4bef-a6c3-b80464aee9dd' WHERE drug_id = 508;
UPDATE drug SET uuid = 'a704474b-e2f7-4201-93a8-4f93885eafe3' WHERE drug_id = 509;
UPDATE drug SET uuid = '55600663-fff9-46ab-90ba-310672a14f61' WHERE drug_id = 513;
UPDATE drug SET uuid = '55600663-fff9-46ab-90ba-310672a14f61' WHERE drug_id = 514;
UPDATE drug SET uuid = '55600663-fff9-46ab-90ba-310672a14f61' WHERE drug_id = 515;
UPDATE drug SET uuid = '55600663-fff9-46ab-90ba-310672a14f61' WHERE drug_id = 516;
UPDATE drug SET uuid = '0185c08b-bd4f-44fc-bc21-423a330efbac' WHERE drug_id = 517;
UPDATE drug SET uuid = '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e' WHERE drug_id = 526;
-- Insert mappings
INSERT INTO eapts_drug_mapping (openmrs_drug_id, dagu_item_uuid, created_date) VALUES  (12, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (13, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (14, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (15, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (18, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (19, 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526', NOW()),
  (28, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (29, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (30, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (31, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (32, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (33, '25d5ba9d-a02f-45d4-9eb5-55687d3a5f02', NOW()),
  (34, '32e586b5-174a-4690-970e-9e40599ff2ba', NOW()),
  (35, '6092bf43-269a-44bb-8eca-b83079ec2ee8', NOW()),
  (36, '6092bf43-269a-44bb-8eca-b83079ec2ee8', NOW()),
  (37, '6092bf43-269a-44bb-8eca-b83079ec2ee8', NOW()),
  (38, '002f0494-c0f0-4118-8184-597c0a4fd895', NOW()),
  (39, '002f0494-c0f0-4118-8184-597c0a4fd895', NOW()),
  (40, '23c32d7f-9586-4446-b17c-35e464e97e15', NOW()),
  (41, '23c32d7f-9586-4446-b17c-35e464e97e15', NOW()),
  (42, '7953e859-386b-4112-9e6e-a88785271b09', NOW()),
  (43, '23c32d7f-9586-4446-b17c-35e464e97e15', NOW()),
  (44, '23c32d7f-9586-4446-b17c-35e464e97e15', NOW()),
  (47, '0f574c10-5a67-49d1-b382-5b07b8d5b9b7', NOW()),
  (48, '0f574c10-5a67-49d1-b382-5b07b8d5b9b7', NOW()),
  (49, 'b093d92f-48d4-477a-8d47-aa498a743fe5', NOW()),
  (50, '77f8e799-b6b4-47ad-8661-a4b4cddf2964', NOW()),
  (51, '77f8e799-b6b4-47ad-8661-a4b4cddf2964', NOW()),
  (63, '8c690c34-0324-4a81-914e-4668f539d152', NOW()),
  (66, '0554d85e-9973-4c75-80f7-66b09edc35a7', NOW()),
  (67, '0554d85e-9973-4c75-80f7-66b09edc35a7', NOW()),
  (68, '104f51e6-d35c-4164-a253-0a96b3b849fb', NOW()),
  (69, '104f51e6-d35c-4164-a253-0a96b3b849fb', NOW()),
  (70, 'a54736e1-7ce1-4e71-a739-ad49ff98b339', NOW()),
  (72, '4f665cf1-e8e8-4c33-89c3-ad195ab9185f', NOW()),
  (73, '4f665cf1-e8e8-4c33-89c3-ad195ab9185f', NOW()),
  (74, '4f665cf1-e8e8-4c33-89c3-ad195ab9185f', NOW()),
  (75, '4f665cf1-e8e8-4c33-89c3-ad195ab9185f', NOW()),
  (77, 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526', NOW()),
  (78, '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e', NOW()),
  (80, '95adca5f-554b-4408-8634-dc7b47b7e5cc', NOW()),
  (85, '63529860-834e-4b40-a2ba-7873614a091c', NOW()),
  (86, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (87, '78b4cb66-4794-4d81-a0b7-2a8fbba5c419', NOW()),
  (88, '1aff9318-6780-40de-8370-36c2418c2993', NOW()),
  (89, '1aff9318-6780-40de-8370-36c2418c2993', NOW()),
  (90, '1aff9318-6780-40de-8370-36c2418c2993', NOW()),
  (91, '1aff9318-6780-40de-8370-36c2418c2993', NOW()),
  (92, '1aff9318-6780-40de-8370-36c2418c2993', NOW()),
  (93, '0c5779f5-f552-4ee1-9b68-d870ea28fb4a', NOW()),
  (94, '0c5779f5-f552-4ee1-9b68-d870ea28fb4a', NOW()),
  (95, '0c5779f5-f552-4ee1-9b68-d870ea28fb4a', NOW()),
  (99, '22d40505-e112-4878-b8d2-579d094214d7', NOW()),
  (100, '07e8ff99-5571-4b26-9ab9-3bb38cca55c6', NOW()),
  (101, '07e8ff99-5571-4b26-9ab9-3bb38cca55c6', NOW()),
  (102, '07e8ff99-5571-4b26-9ab9-3bb38cca55c6', NOW()),
  (103, '07e8ff99-5571-4b26-9ab9-3bb38cca55c6', NOW()),
  (104, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (105, 'fab228c6-ca7f-4d1a-abe8-f7ef2664b5b8', NOW()),
  (106, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (107, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (108, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (109, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (110, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (111, '0f312df0-4cfd-4774-9666-a05f3da7a35d', NOW()),
  (112, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (113, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (114, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (115, '78b4cb66-4794-4d81-a0b7-2a8fbba5c419', NOW()),
  (116, '0e77cc78-2967-4073-9b7f-40d641259af6', NOW()),
  (117, '0e77cc78-2967-4073-9b7f-40d641259af6', NOW()),
  (118, '124bcd41-f2d9-43f8-bbf8-3bb55b1c3e3a', NOW()),
  (119, 'a411cbd3-df5a-4ce1-a004-098fb6f52fe9', NOW()),
  (123, '479e66e8-5b86-4a45-8066-52f4db4164a6', NOW()),
  (124, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (125, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (126, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (127, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (128, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (129, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (130, '4f119f61-938f-4e37-893a-450b9edca202', NOW()),
  (131, '0a549ecc-a7c0-4e87-8e71-dde09483655e', NOW()),
  (132, '003b0694-c0cd-43cf-abee-86aae6992b96', NOW()),
  (133, '4edc1934-0f23-4faf-a5eb-7422b5ec5940', NOW()),
  (134, '4edc1934-0f23-4faf-a5eb-7422b5ec5940', NOW()),
  (135, '4edc1934-0f23-4faf-a5eb-7422b5ec5940', NOW()),
  (136, '4edc1934-0f23-4faf-a5eb-7422b5ec5940', NOW()),
  (137, '3ddac5dc-b117-4d11-a01e-ae123060510f', NOW()),
  (138, '3ddac5dc-b117-4d11-a01e-ae123060510f', NOW()),
  (139, '3ddac5dc-b117-4d11-a01e-ae123060510f', NOW()),
  (142, '5aff73f2-d53d-473c-a23b-4d34a7dad1f4', NOW()),
  (143, '5aff73f2-d53d-473c-a23b-4d34a7dad1f4', NOW()),
  (144, '5aff73f2-d53d-473c-a23b-4d34a7dad1f4', NOW()),
  (145, '5aff73f2-d53d-473c-a23b-4d34a7dad1f4', NOW()),
  (146, 'fdcac0df-1cf0-4ef0-8641-4fdbd5fc6cfa', NOW()),
  (147, 'fdcac0df-1cf0-4ef0-8641-4fdbd5fc6cfa', NOW()),
  (148, 'fdcac0df-1cf0-4ef0-8641-4fdbd5fc6cfa', NOW()),
  (149, 'e70caf0b-f17c-4acc-9321-4891ce302597', NOW()),
  (150, 'e70caf0b-f17c-4acc-9321-4891ce302597', NOW()),
  (151, '4e17f09e-1e15-4d21-8b0a-34277d61d41a', NOW()),
  (152, '4e17f09e-1e15-4d21-8b0a-34277d61d41a', NOW()),
  (153, '4e17f09e-1e15-4d21-8b0a-34277d61d41a', NOW()),
  (154, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (155, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (156, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (157, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (158, '324a63ce-ee32-44f0-aac6-7d240e3041fe', NOW()),
  (159, '324a63ce-ee32-44f0-aac6-7d240e3041fe', NOW()),
  (160, '324a63ce-ee32-44f0-aac6-7d240e3041fe', NOW()),
  (161, '324a63ce-ee32-44f0-aac6-7d240e3041fe', NOW()),
  (162, '11223f2a-e361-437a-8328-37b2e7234466', NOW()),
  (163, '11223f2a-e361-437a-8328-37b2e7234466', NOW()),
  (164, 'e84f1938-aca7-4217-a99d-dbe879772273', NOW()),
  (165, '11223f2a-e361-437a-8328-37b2e7234466', NOW()),
  (166, '20c66d34-5a48-482b-b132-5ba37c7a65e8', NOW()),
  (167, '20c66d34-5a48-482b-b132-5ba37c7a65e8', NOW()),
  (168, '20c66d34-5a48-482b-b132-5ba37c7a65e8', NOW()),
  (169, '1fb54d96-33ae-4f46-9542-1f98c923b394', NOW()),
  (170, '48664ddb-6229-4cde-ab1a-647d0da6cdff', NOW()),
  (171, '3f126a01-64dd-4674-80a2-f48077645c34', NOW()),
  (172, '089ac445-a53a-4415-b7ae-0c706c43e902', NOW()),
  (173, '089ac445-a53a-4415-b7ae-0c706c43e902', NOW()),
  (174, '9632bae1-83ff-430c-84da-583e96ccfc46', NOW()),
  (182, '0bf8ec68-b606-4111-98eb-35eb3452be72', NOW()),
  (183, '0bf8ec68-b606-4111-98eb-35eb3452be72', NOW()),
  (185, '717d2642-a4c2-4c50-868e-5c025d8e18a9', NOW()),
  (186, '5bac4519-ca41-47dc-b445-2d329ece9c3a', NOW()),
  (187, '0151c78f-a53d-4ebe-afe2-b0e652827db7', NOW()),
  (188, '0151c78f-a53d-4ebe-afe2-b0e652827db7', NOW()),
  (189, '0151c78f-a53d-4ebe-afe2-b0e652827db7', NOW()),
  (190, '0151c78f-a53d-4ebe-afe2-b0e652827db7', NOW()),
  (191, '0151c78f-a53d-4ebe-afe2-b0e652827db7', NOW()),
  (192, '5bac4519-ca41-47dc-b445-2d329ece9c3a', NOW()),
  (193, '4bbb95a3-9f49-4b65-b462-fc247db1fab0', NOW()),
  (194, '4bbb95a3-9f49-4b65-b462-fc247db1fab0', NOW()),
  (195, '4bbb95a3-9f49-4b65-b462-fc247db1fab0', NOW()),
  (196, '073674e3-35a7-4fcc-9317-611d8d5b532d', NOW()),
  (197, '073674e3-35a7-4fcc-9317-611d8d5b532d', NOW()),
  (198, '073674e3-35a7-4fcc-9317-611d8d5b532d', NOW()),
  (199, '073674e3-35a7-4fcc-9317-611d8d5b532d', NOW()),
  (200, '073674e3-35a7-4fcc-9317-611d8d5b532d', NOW()),
  (209, '18702c41-e66d-455e-bf4b-35099adb04dc', NOW()),
  (210, '089ac445-a53a-4415-b7ae-0c706c43e902', NOW()),
  (213, '098bbf71-34cf-4582-925d-7998bb75ef7f', NOW()),
  (214, '20365026-a221-4d9d-8160-3f2cdb17000b', NOW()),
  (215, '20365026-a221-4d9d-8160-3f2cdb17000b', NOW()),
  (216, '20365026-a221-4d9d-8160-3f2cdb17000b', NOW()),
  (217, '20365026-a221-4d9d-8160-3f2cdb17000b', NOW()),
  (218, '16cf30d5-24b4-4b3e-88ce-19ec1ea19772', NOW()),
  (219, '16cf30d5-24b4-4b3e-88ce-19ec1ea19772', NOW()),
  (220, '16cf30d5-24b4-4b3e-88ce-19ec1ea19772', NOW()),
  (221, '16cf30d5-24b4-4b3e-88ce-19ec1ea19772', NOW()),
  (222, '16cf30d5-24b4-4b3e-88ce-19ec1ea19772', NOW()),
  (223, '16cf30d5-24b4-4b3e-88ce-19ec1ea19772', NOW()),
  (224, '16cf30d5-24b4-4b3e-88ce-19ec1ea19772', NOW()),
  (228, '1d9e1df4-8aea-4973-a82e-cf781fe6019f', NOW()),
  (229, '1d9e1df4-8aea-4973-a82e-cf781fe6019f', NOW()),
  (230, '12c84b53-f884-42df-83a9-14d32808d233', NOW()),
  (231, '12c84b53-f884-42df-83a9-14d32808d233', NOW()),
  (232, '12c84b53-f884-42df-83a9-14d32808d233', NOW()),
  (242, '1e5a30ad-627c-4094-904d-eaa6df904d91', NOW()),
  (243, '1e5a30ad-627c-4094-904d-eaa6df904d91', NOW()),
  (244, '1e5a30ad-627c-4094-904d-eaa6df904d91', NOW()),
  (245, 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9', NOW()),
  (246, 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9', NOW()),
  (247, '7a46c8f1-4ae8-4e06-9246-edf5ceb5d73f', NOW()),
  (254, '00e31734-ce75-4354-98fb-ab3a35dd71e9', NOW()),
  (255, '1209780f-80c9-4397-9d54-1cfca2c3b9f0', NOW()),
  (257, '002f0494-c0f0-4118-8184-597c0a4fd895', NOW()),
  (258, 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9', NOW()),
  (276, '1bfdbc7a-96a5-42e4-9aab-c45b94750949', NOW()),
  (277, '1bfdbc7a-96a5-42e4-9aab-c45b94750949', NOW()),
  (278, '1bfdbc7a-96a5-42e4-9aab-c45b94750949', NOW()),
  (279, '1bfdbc7a-96a5-42e4-9aab-c45b94750949', NOW()),
  (289, '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4', NOW()),
  (290, '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4', NOW()),
  (291, '1daa178c-3cb4-4052-bb2c-fcbfe87e93e4', NOW()),
  (292, '414d23db-7f64-494b-bc47-864642267708', NOW()),
  (293, '414d23db-7f64-494b-bc47-864642267708', NOW()),
  (294, '0bfed41e-4163-48dd-bd3a-8a0d2bd7b17a', NOW()),
  (295, '0bfed41e-4163-48dd-bd3a-8a0d2bd7b17a', NOW()),
  (296, '012b142a-c84a-40bd-8e0a-847d27e5c651', NOW()),
  (297, '012b142a-c84a-40bd-8e0a-847d27e5c651', NOW()),
  (299, '0ea731fb-c47e-44e5-8499-8e159e9fe912', NOW()),
  (300, '0ea731fb-c47e-44e5-8499-8e159e9fe912', NOW()),
  (310, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (311, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (312, '788f1cdd-e663-40d5-85bb-4ef7fa09967d', NOW()),
  (319, 'dabd4d3a-0d27-48b7-89fd-13a2801efa8e', NOW()),
  (320, 'bdac07c7-5e9b-4c42-bc1e-be1d9c9cf726', NOW()),
  (321, 'bdac07c7-5e9b-4c42-bc1e-be1d9c9cf726', NOW()),
  (322, 'c8a317cd-4bfb-4041-971b-dec17c98b297', NOW()),
  (323, 'c8a317cd-4bfb-4041-971b-dec17c98b297', NOW()),
  (325, '39552d94-e958-4370-a622-8eedb8dcedaf', NOW()),
  (326, '39552d94-e958-4370-a622-8eedb8dcedaf', NOW()),
  (328, 'b5a92c9a-02ae-4b70-9e21-8adc0e65a20d', NOW()),
  (330, '319a345f-8351-4bd5-8d3d-c624adc0f11a', NOW()),
  (332, 'd4f86398-1199-4431-a7fd-b7f8046dcbf4', NOW()),
  (336, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (343, '550c2a8d-21d3-4ded-aee8-a653a68ae97f', NOW()),
  (346, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (350, '012b142a-c84a-40bd-8e0a-847d27e5c651', NOW()),
  (353, '0e09edd4-a194-461c-a010-aa44bd1c50db', NOW()),
  (354, '0e09edd4-a194-461c-a010-aa44bd1c50db', NOW()),
  (355, '717d2642-a4c2-4c50-868e-5c025d8e18a9', NOW()),
  (356, 'a2e2d9cb-179e-45bc-8e4a-c9160407e96d', NOW()),
  (357, 'a2e2d9cb-179e-45bc-8e4a-c9160407e96d', NOW()),
  (372, '88b852e6-b43b-4071-b057-1b1fe00a8e79', NOW()),
  (373, '88b852e6-b43b-4071-b057-1b1fe00a8e79', NOW()),
  (374, '49e297b4-6f01-4b71-8ffb-bc014bb806f4', NOW()),
  (375, '542656b9-0c1e-4d8b-896e-9f0e8e3cd0b0', NOW()),
  (378, '548aecc2-84b2-444e-a896-17ab7a01e02f', NOW()),
  (379, 'a54736e1-7ce1-4e71-a739-ad49ff98b339', NOW()),
  (380, 'a54736e1-7ce1-4e71-a739-ad49ff98b339', NOW()),
  (381, 'a54736e1-7ce1-4e71-a739-ad49ff98b339', NOW()),
  (386, '4f665cf1-e8e8-4c33-89c3-ad195ab9185f', NOW()),
  (387, '5326364f-8c9a-48fe-9a3d-46b44da82d2f', NOW()),
  (388, '5326364f-8c9a-48fe-9a3d-46b44da82d2f', NOW()),
  (391, 'ac2b070b-c362-4314-8d5b-1899c297ec4d', NOW()),
  (394, '043bac44-b808-4c62-acae-f83b6dd2ef09', NOW()),
  (395, '57228cdc-2269-44ea-ad2d-65a92f03e12a', NOW()),
  (396, '245a5c30-f5c8-4394-b89e-57fd71faa4a1', NOW()),
  (397, '245a5c30-f5c8-4394-b89e-57fd71faa4a1', NOW()),
  (398, '245a5c30-f5c8-4394-b89e-57fd71faa4a1', NOW()),
  (399, '043bac44-b808-4c62-acae-f83b6dd2ef09', NOW()),
  (400, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (412, '073674e3-35a7-4fcc-9317-611d8d5b532d', NOW()),
  (413, '11223f2a-e361-437a-8328-37b2e7234466', NOW()),
  (414, '11223f2a-e361-437a-8328-37b2e7234466', NOW()),
  (415, '3f130339-2f34-4850-b88b-94de606df3a1', NOW()),
  (416, '3a52076c-d186-4aae-9d7a-901e52b27998', NOW()),
  (417, 'c8a317cd-4bfb-4041-971b-dec17c98b297', NOW()),
  (418, 'c8a317cd-4bfb-4041-971b-dec17c98b297', NOW()),
  (419, '4f665cf1-e8e8-4c33-89c3-ad195ab9185f', NOW()),
  (420, '4f665cf1-e8e8-4c33-89c3-ad195ab9185f', NOW()),
  (427, 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526', NOW()),
  (428, 'd21d85ee-4c10-49b4-8c59-5e0b30b5e526', NOW()),
  (430, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (431, '143f94c0-774f-41f2-9b12-13dc97cffd4f', NOW()),
  (440, '9d2a779a-0bae-4592-9b21-50fa03a276fa', NOW()),
  (441, '9d2a779a-0bae-4592-9b21-50fa03a276fa', NOW()),
  (442, '23fe72a4-72de-45a2-b627-bafac382e3e1', NOW()),
  (443, '23fe72a4-72de-45a2-b627-bafac382e3e1', NOW()),
  (444, '39552d94-e958-4370-a622-8eedb8dcedaf', NOW()),
  (445, '1d9cb705-5210-4597-8c0a-479ccc0630cc', NOW()),
  (450, '3735c2b1-42a0-452e-8e5c-7b98490fd429', NOW()),
  (451, '3735c2b1-42a0-452e-8e5c-7b98490fd429', NOW()),
  (452, '3735c2b1-42a0-452e-8e5c-7b98490fd429', NOW()),
  (453, '3735c2b1-42a0-452e-8e5c-7b98490fd429', NOW()),
  (459, '069bcc18-902c-4030-9030-0b3e723383a4', NOW()),
  (476, 'a54736e1-7ce1-4e71-a739-ad49ff98b339', NOW()),
  (477, 'a54736e1-7ce1-4e71-a739-ad49ff98b339', NOW()),
  (480, '36721b44-3dc5-4436-8609-a15d3cb1d757', NOW()),
  (481, '36721b44-3dc5-4436-8609-a15d3cb1d757', NOW()),
  (482, '36721b44-3dc5-4436-8609-a15d3cb1d757', NOW()),
  (483, '80daa25a-d28c-45a0-9816-2adbd9374975', NOW()),
  (484, '36721b44-3dc5-4436-8609-a15d3cb1d757', NOW()),
  (487, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (488, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (489, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (490, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (491, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (492, '63529860-834e-4b40-a2ba-7873614a091c', NOW()),
  (493, '63529860-834e-4b40-a2ba-7873614a091c', NOW()),
  (494, '0f77d4c2-9eba-4749-87df-7a0cba14698d', NOW()),
  (495, '003b0694-c0cd-43cf-abee-86aae6992b96', NOW()),
  (496, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (497, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (498, '20742023-34b0-4b3a-9693-506174af1bcc', NOW()),
  (499, 'f9609cca-2a9e-4308-8b58-1452f7ec1ab9', NOW()),
  (500, '002f0494-c0f0-4118-8184-597c0a4fd895', NOW()),
  (501, '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e', NOW()),
  (502, '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e', NOW()),
  (507, 'a704474b-e2f7-4201-93a8-4f93885eafe3', NOW()),
  (508, '6336a316-3c94-4bef-a6c3-b80464aee9dd', NOW()),
  (509, 'a704474b-e2f7-4201-93a8-4f93885eafe3', NOW()),
  (513, '55600663-fff9-46ab-90ba-310672a14f61', NOW()),
  (514, '55600663-fff9-46ab-90ba-310672a14f61', NOW()),
  (515, '55600663-fff9-46ab-90ba-310672a14f61', NOW()),
  (516, '55600663-fff9-46ab-90ba-310672a14f61', NOW()),
  (517, '0185c08b-bd4f-44fc-bc21-423a330efbac', NOW()),
  (526, '3ae8d791-f4ce-4d7d-a8fe-56fe3ee59e7e', NOW());
-- Update sequence
SET FOREIGN_KEY_CHECKS = 1;
